// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robots.subsystems;


import frc.robots.RobotMap;
import frc.robots.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DoubleSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Claw extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // private Solenoid clawActuator;
    private DoubleSolenoid clawActuator;

    public Claw() {
        // clawActuator = new Solenoid(RobotMap.CLAW_ACTUATOR_CHANNEL_NUMBER);
        // clawActuator.set(false);

        clawActuator = new DoubleSolenoid(RobotMap.PCM_MODULE_NUMER, RobotMap.CLAW_ACTUATOR_FORWARD_CHANNEL, RobotMap.CLAW_ACTUATOR_REVERSE_CHANNEL);
        addChild("ClawActuator",clawActuator);

        clawActuator.set(Value.kReverse);
        
        
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // public void setClawActuatorOut() {
    //     clawActuator.set(true);
    // }

    // public void setClawActuatorIn() {
    //     clawActuator.set(false);
    // }

    // public boolean isClawActuatorOn() {
    //     return clawActuator.get();
    // }

    public boolean isClawActuatorForward() {
        if(clawActuator.get() == Value.kForward) {
            return true;
        }
        return false;
    }

    public void setClawActuatorIn() {
        clawActuator.set(Value.kReverse);
    }

    public void setClawActuatorOut() {
        clawActuator.set(Value.kForward);
    }

    public void doClawActuator() {
        if(!isClawActuatorForward()) {
            setClawActuatorOut();
          } else {
            setClawActuatorIn();
          }
    }



    

    // public void setClawActuatorOff() {
    //     clawActuator.set(DoubleSolenoid.Value.kOff);
    // }

}

